name: Docker Image CI
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-20.04
    outputs:
      docker-image-tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Get info
        run: |
          echo "pwd: $(pwd)"
          ls
          ls ${{ github.workspace }}

      - name: Set docker username -> "steps.docker-user-name.outputs.user-name"
        id: docker-user-name
        run: echo "::set-output name=user-name::avhb"
      - name: Set docker image name -> "steps.docker-image-name.outputs.image-name"
        id: docker-image-name
        run: echo "::set-output name=image-name::demo-app"
      - name: Get short commit id -> "steps.git-commit-id.outputs.commit-id"
        id: git-commit-id
        run: echo "::set-output name=commit-id::$(git rev-parse --short HEAD)"
      - name: Create docker tag -> steps.docker-tag.outputs.tag 
        id: docker-tag
        run: echo "::set-output name=tag::${{ steps.docker-user-name.outputs.user-name }}/${{ steps.docker-image-name.outputs.name }}:${{ steps.git-commit-id.outputs.commit-id }}"
    
      - name: Build the Docker image
        run: |
          pushd app
          docker build . --file Dockerfile --tag ${{ steps.docker-tag.outputs.tag }}
          popd

      - run: docker images
      
      - name: Start the image
        run: docker run -d -p 5000:5000 ${{ steps.docker-tag.outputs.tag }}
      - name: Check with curl that image is running
        run: for i in 1 2 3 4 5 6 7 8 9 10; do curl http://127.0.0.1:5000/ && break || sleep 1; done

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: avhb
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

       - name: Push into Docker Hub
         run: docker push ${{ steps.docker-tag.outputs.tag }}

  Publish-Docker-Image:
    needs: Build-Docker-Image
    runs-on: ubuntu-20.04
    steps:
      - name: INFO - docker images
        run: docker images
      - run: echo ${{ needs.Build-Docker-Image.outputs.docker-image-tag }}






# - name: Cleanup docker environment (removing all containers and images)
      #   run: | 
      #     if [[ $(docker ps -aq | wc -l) -ne 0 ]]; then docker stop $(docker ps -aq) && docker rm $(docker ps -aq); fi
      #     if [[ $(docker images -q | wc -l) -ne 0 ]]; then docker image rm --force $(docker images -q); fi
