name: Docker Image CI
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: self-hosted
    steps:
      - name: cleanup docker environment
        run: | 
          if [[ $(docker ps -aq | wc -l) -ne 0 ]]; then docker stop $(docker ps -aq) && docker rm $(docker ps -aq); fi
          if [[ $(docker images -q | wc -l) -ne 0 ]]; then docker image rm --force $(docker images -q); fi
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag demo-app
      - run: docker save demo-app > demo-app_save.tar
      - run: ls
      - run: pwd
      - run: docker images
      - name: start the image
        run: docker run -d -p 5000:5000 demo-app
      #- name: get the smoketest - it is in the same repo


      #create selenium grid clients with docker



        # - create a new 
      #- run: ping 10.200.20.222


