name: Docker Image CI
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get info
        run: |
          echo "job triggered by - ${{ github.event_name }}"
          echo "job running on ${{ runner.os }} server hosted by GitHub!"
          echo "branch name - ${{ github.ref }}, repo - ${{ github.repository }}"
          echo "job status - ${{ job.status }}."
          echo "pwd: $(pwd)"
          ls ${{ github.workspace }}
      
      # - name: Cleanup docker environment (removing all containers and images)
      #   run: | 
      #     if [[ $(docker ps -aq | wc -l) -ne 0 ]]; then docker stop $(docker ps -aq) && docker rm $(docker ps -aq); fi
      #     if [[ $(docker images -q | wc -l) -ne 0 ]]; then docker image rm --force $(docker images -q); fi
      
      - name: Create timestamped docker tag
        id: docker-tag
        run: echo "::set-output name=docker-tag::demo-app:$(date '+%Y%m%d%T')"

      - name: Build the Docker image
        run: |
          pushd app
          docker build . --file Dockerfile --tag ${{ steps.date.outputs.date }}
          popd
      
      # - name: Export the docker image as tar file
      #   run: docker save demo-app > demo-app_save.tar
      
      - name: INFO - docker images
        run: docker images
      
      - name: Start the image
        run: docker run -d -p 5000:5000 demo-app
      
      - name: Check with curl that image is running
        run: curl http://127.0.0.1:5000/
      - run: echo "::set-output name=action_fruit::strawberry"
      - name: Cleanup docker environment (removing all containers and images)
        if: always()
        run: | 
          if [[ $(docker ps -aq | wc -l) -ne 0 ]]; then docker stop $(docker ps -aq) && docker rm $(docker ps -aq); fi
          if [[ $(docker images -q | wc -l) -ne 0 ]]; then docker image rm --force $(docker images -q); fi
          docker images
      #- name: get the smoketest - it is in the same repo
  Publish-Docker-Image:
    needs: Build-Docker-Image
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: echo hello world
      - run: echo ${{ action_fruit }}
      - run: echo ${{ secrets.GHCR_KEY }}

      #create selenium grid clients with docker



        # - create a new 
      #- run: ping 10.200.20.222


